export const SET_USER = 'SET_USER'
export const SET_USERS = 'SET_USERS'
export const SET_PROFILE = 'SET_PROFILE'
export const SET_NAME_EXIST = 'SET_NAME_EXIST'
export const SET_URL_EXIST = 'SET_URL_EXIST'

export const SET_BITE = 'SET_BITE'
export const SET_BITES = 'SET_BITES'
export const SET_BITE_THUMBNAILS = 'SET_BITE_THUMBNAILS'
export const SET_BITE_INITIAL = 'SET_BITE_INITIAL'

export const SET_LOADING_TRUE = 'SET_LOADING_TRUE'
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE'

export const GET_SOCIAL_ACCOUNTS = 'GET_SOCIAL_ACCOUNTS'
export const ADD_SOCIAL_ACCOUNTS = 'ADD_SOCIAL_ACCOUNTS'
export const DELETE_SOCIAL_ACCOUNTS = 'DELETE_SOCIAL_ACCOUNTS'

export const SET_USER_INITIAL = 'SET_USER_INITIAL'
export const SET_STRIPEID = 'SET_STRIPEID'
export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_PREVIOUS_ROUTE = 'SET_PREVIOUS_ROUTE'
export const SET_DIALOG_STATE = 'SET_DIALOG_STATE'
export const SET_CURRENCY_RATE = 'SET_CURRENCY_RATE'
