export const SET_USER = 'SET_USER'
export const SET_USERS = 'SET_USERS'
export const SET_PROFILE = 'SET_PROFILE'
export const SET_NAME_EXIST = 'SET_NAME_EXIST'
export const SET_URL_EXIST = 'SET_URL_EXIST'

export const SET_BITE = 'SET_BITE'
export const SET_BITES = 'SET_BITES'
export const SET_BITE_INITIAL = 'SET_BITE_INITIAL'

export const SET_VIDEO_ALIGNS = 'SET_VIDEO_ALIGNS'
export const SET_SELECTED_INDEXES = 'SET_SELECTED_INDEXES'

export const SET_LOADING_TRUE = 'SET_LOADING_TRUE'
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE'
export const SET_UPLOADING = 'SET_UPLOADING'

export const SET_SOCIAL_ACCOUNT = 'SET_SOCIAL_ACCOUNT'

export const SET_USER_INITIAL = 'SET_USER_INITIAL'
export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_PREVIOUS_ROUTE = 'SET_PREVIOUS_ROUTE'
export const SET_DIALOG_STATE = 'SET_DIALOG_STATE'
export const SET_CURRENCY_RATE = 'SET_CURRENCY_RATE'

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'

export const SET_PAYMENT_INITIAL = 'SET_PAYMENT_INITIAL'
export const SET_PAYMENT = 'SET_PAYMENT'

export const SET_UPLOADED_PROCESS = 'SET_UPLOADED_PROCESS'

export const SET_TERMS_AND_PRIVACY = 'SET_TERMS_AND_PRIVACY'
